---
namespace: nccurry
name: openshift
version: 1.3.0
readme: README.md
authors:
- Nick Curry <code@nickcurry.com>
description: Collection to administer OpenShift / OKD clusters
license_file: 'LICENSE'
tags:
- openshift
- okd
- kubernetes
- red
- hat
- coreos
- oc
- container
- docker
- podman
dependencies: {}
repository: https://github.com/nccurry/nccurry.openshift
documentation: ''
homepage: ''
issues: https://github.com/nccurry/nccurry.openshift/issues/tracker
build_ignore:
- '*.tar.gz'

