---
name: Release and deploy collection
on: # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  releaseanddeploy:
    runs-on: ubuntu-20.04
    if: github.repository == 'nccurry/nccurry.openshift'
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: cversion
        run: echo "::set-output name=version::$(grep version galaxy.yml | awk '{ print $2 }')"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade ansible

      - name: Copy files and directories to source
        run: |
          mkdir -p build/src
          cp $files build/src
          cp -rf $directories build/src
        env:
          files: "README.md LICENSE galaxy.yml"
          directories: "roles"

      - name: Build Ansible collection
        run: ansible-galaxy collection build build/src --force

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.cversion.outputs.version }}
          release_name: Release v${{ steps.cversion.outputs.version }}
          body: |
            # Ansible Collection: nccurry.openshift
            Install with:
            ```sh
            ansible-galaxy collection install -r requirements.yml -f
            ```
            The requirements.yml needs to have the following format and content:
            ```yaml
            ---
            collections:
                - https://github.com/nccurry/nccurry.openshift/releases/download/v${{ steps.cversion.outputs.version }}/nccurry-openshift-${{ steps.cversion.outputs.version }}.tar.gz
            ```
          draft: false
          prerelease: false

      - name: Upload release Asset
        id: upload-release-asset
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: nccurry-openshift-${{ steps.cversion.outputs.version }}.tar.gz
          asset_name: nccurry-openshift-${{ steps.cversion.outputs.version }}.tar.gz
          asset_content_type: application/tar+gzip

      - name: Deploy Ansible collection to Galaxy Dev
        if: github.ref == 'refs/heads/development'
        run: ansible-galaxy collection publish nccurry-openshift-${{ steps.cversion.outputs.version }}.tar.gz --server https://galaxy-dev.ansible.com/ --api-key ${{ secrets.GALAXYDEV_API_KEY }}

#      - name: Deploy Ansible collection to Galaxy
#        if: github.ref == 'refs/heads/master'
#        run: ansible-galaxy collection publish nccurry-openshift-${{ steps.cversion.outputs.version }}.tar.gz --api-key ${{ secrets.GALAXYDEV_API_KEY }}
